### PR TITLE
Rename UserReport module to UserReportSDK

### LINKED ISSUE #4: Conflicting namespace with User
User is really generic class name to have and I bet that most applications are already using it.
The module is called UserReport and the SDK also has class called UserReport so we can't tell which User we want to initialise.

e.g. this can't be done
```swift
UserReport.User() // Type 'UserReport' has no member 'User'
```
and these are failing as well
```swift
User() // Uses our User object
UserReport.configure(sakId: "", mediaId: "", user: User) // Try to use our User object
```

If we can't access the module's namespace, all the generic classes should be reviewed and possibly prefixed. Or make the namespace accessible.

### PR DESCRIPTION
**Pull request by swordfishyou**
Resolves #4

### CODE REVIEW

**Review by hmvs — APPROVED** [review]

**Comment by pyrtsa** [comment]
I think this PR forgot to change the `import` in the README accordingly, btw.

**Comment by hmvs** [comment]
import hasn't changed here. we've renamed the `User` class instead.

**Comment by hmvs** [comment]
import hasn't changed here. we've renamed the `User` class instead. As far as we realized that documentation is already sent we couldn't change the name of the module.

**Comment by pyrtsa** [comment]
Ok, I see. I was under the impression you were following semver.org and that before 1.0 everything could be breaking. But fair enough then.

**Pull request merged**
